[package]
name = "minimum-spanning-tree"
version = "0.1.0"
edition = "2021"

[lib]
name = "minimum_spanning_tree"
path = "src/lib.rs"
doctest = false


[dependencies]
bit-set = "0.8.0"
csv = "1.3.1"
rayon = "1.10.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
