[package]
name = "transportation-problem"
version = "0.1.0"
edition = "2021"

[lib]
name = "transportation_problem"
path = "src/lib.rs"
doctest = false

[dependencies]
rand = "0.8.5"
rstest = "0.23.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
